# Generated by Django 3.2.2 on 2022-04-13 03:41

import api.models.couching_staff
import api.models.player
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
                ('last_name', models.TextField(max_length=45)),
                ('birthday', models.DateField()),
                ('position', models.TextField(max_length=45)),
                ('shirt_number', models.IntegerField(validators=[api.models.player.validate_shirt_number])),
                ('is_titular', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='CouchingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
                ('last_name', models.TextField(max_length=45)),
                ('birthday', models.DateField()),
                ('birth_country', models.TextField(max_length=45)),
                ('rol', models.TextField(validators=[api.models.couching_staff.validate_rol])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
