# Generated by Django 3.2.2 on 2022-04-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_titular',
            field=models.BooleanField(),
        ),
    ]
