# Generated by Django 3.2.2 on 2022-04-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_player_is_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(null=True, upload_to='player-photos'),
        ),
        migrations.AddField(
            model_name='team',
            name='flag',
            field=models.ImageField(null=True, upload_to='team-flags'),
        ),
        migrations.AddField(
            model_name='team',
            name='shield',
            field=models.ImageField(null=True, upload_to='team-shields'),
        ),
    ]
