# Generated by Django 2.2.12 on 2022-04-13 21:05

import api.models.couching_staff
import api.models.player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220413_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='shield',
        ),
        migrations.AddField(
            model_name='team',
            name='shell',
            field=models.ImageField(null=True, upload_to='team-shell'),
        ),
        migrations.AlterField(
            model_name='couchingstaff',
            name='birthday',
            field=models.DateField(validators=[api.models.couching_staff.validate_birthday]),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(validators=[api.models.player.validate_birthday]),
        ),
    ]
